### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Netherzapdos** [Netherzapdos/axolotl-game#2]
### **SFL Axolotls Roadmap**
---
**Skeleton**
- [x] Map Collisions (11/6/22)
- [x] Player Movement (11/8/22)
- [x] Player Movement (Sprint mode) (11/20/22)
- [x] Add In-game Mouse Pointer/Cursor for Interactions (11/29/22)
- [x] Make things interactable only when the character is close enough (12/1/22) https://labs.phaser.io/edit.html?src=src\3.60\physics\matterjs\compound%20sensors.js
- [x] NPC Proximity Detectors/Sensors (12/1/22) 
- [ ] NPC Dialogue Modal (Conversation) 
- [ ] NPC Dialogue Modal (Yes/No)
==================================================================
- [ ] Game Logo 
- [x] Main Menu (11/27/22)
- [x] Animated Main Menu https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_breakout_game_Phaser/Animations_and_tweens https://phaser.io/examples/v2/basics/07-tween-an-image (11/30/22)
- [ ] Main Menu Transitions https://blog.ourcade.co/posts/2020/phaser-3-fade-out-scene-transition/
==================================================================
- [ ] Creating, Storing and Fetching Data https://phaser.io/examples/v3/category/components/data
- [ ] Save System
- [ ] Basic Game States to Keep Track of Progress
- [ ] Base Map
==================================================================
- [ ] Launch online using Firebase (12/14/22)
- [ ] Design webpage
---

**Skeleton 2**
- [ ] Auto Save Data
- [ ] Animated Mouse Pointers/Cursors for on-hover effects (https://stackoverflow.com/questions/71132482/phaser-3-custom-animated-cursor-not-working) https://phaser.io/examples/v3/view/input/cursors/custom-cursor
- [ ] Building Modal

**Gameplay**
- [ ] Add button that enables/disables mobile controls. 
- [ ] Day Time/Night Time https://www.joshmorony.com/how-to-create-a-day-night-cycle-in-phaser/
==================================================================
- [ ] Inventory System
- [ ] Resource Gathering (Chopping)
- [ ] Resource Gathering (Mining)
- [ ] Resource Gathering (Fishing)
- [ ] Resource Gathering (Item drops)
==================================================================
- [ ] Planting System
- [ ] Logic that keeps track of how much time has passed since the first time a plant was planted
==================================================================
- [ ] Phaser 3 Proximity (Calculate distance between player and x and only initiate interactions w/in certain distance) 
- [ ] Phaser 3 Sensor (Detect if player is within a certain area/region and play ambient music, change UI, play weather, etc respective to that area/region)
==================================================================
- [ ] Objective Markers w/ w/o Distance Trackers
- [ ] Map/Mini Map
- [ ] Map (Custom Markers w/ Distance Trackers)
---

**Gameplay 2**
- [ ] Crafting System
- [ ] Axolotl Spawning https://www.youtube.com/watch?v=_MAKw363UMk&ab_channel=WiLD
- [ ] Axolotl Taming
- [ ] Axolotl Keeping & Caring System
- [ ] Axolotl Hearts (Currency)
- [ ] Building Interactions & Upgrades using Axol Hearts
---

**Misc**
- [ ] Random Menu Messages
- [ ] Random NPC Idle Dialogues
- [ ] Random Cloud Generator
---
Phaser 3 

Tweens Properties https://rexrainbow.github.io/phaser3-rex-notes/docs/site/tween/

Pointer Events https://rexrainbow.github.io/phaser3-rex-notes/docs/site/touchevents/

**Comment by Netherzapdos** [comment]
### **Nov. 8, 2022**
---
**Player Movement**
- Finished, however ghost collisions exist. Unfortunately this is a side effect of the MatterJS engine in which it cannot handle such collisions. 
- Recommended/possible solution: Arcade Physics _may_ handle it better. Otherwise, a user suggested merging all collisions into one big, singular collision layer to remove intersecting collision tiles where ghost collisions occur.

**Comment by Netherzapdos** [comment]
> ### **Nov. 8, 2022**
> **Player Movement**
> 
> * Finished, however ghost collisions exist. Unfortunately this is a side effect of the MatterJS engine in which it cannot handle such collisions.
> * Recommended/possible solution: Arcade Physics _may_ handle it better. Otherwise, a user suggested merging all collisions into one big, singular collision layer to remove intersecting collision tiles where ghost collisions occur.

https://phaser.io/examples/v3/view/tilemap/collision/matter-ghost-collisions

**Comment by Netherzapdos** [comment]
### Dec 14, 2022 - Firebase Issues
---
- dlist folder needs to be in public, same as the public folder where the new index.html got added when the build version was made using `npm run build`

- PressStart2P font path was wrong in the build version css file

**Comment by Netherzapdos** [comment]
Inventory system
- when the image of the item is clicked, use: 

nameOfItemEquipped = true

and then if used for, i.e mining

if (pickaxeIsEquipped == true) {
code
} else {
return
}

idk jos an idea
